require("lazy-packages")
require("lspformatter")
require("package-config.init")
require("keybinding.init")
vim.cmd.colorscheme "catppuccin"
vim.cmd("set relativenumber")
vim.cmd("set tabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set expandtab")
vim.api.nvim_set_option("clipboard","unnamed")
