require("package-config.lualine")
require("package-config.tabline")
require("package-config.nvimtree")
require("package-config.nvim-cmp")
require("package-config.autoclose")
require("package-config.telescope")
require("package-config.treesitter-context")
require("package-config.lazy-git")
